version: '3'

services:

  covid:
    
    image: kerxd/covid-19:latest

    container_name: docker-covid

    environment:
      - SERVER_PORT=80

    ports:
      - "88:80"

    networks: 
      - covid-network

    depends_on:
      - mysqldb



  mysqldb:
    image: mysql:8

    container_name: docker-mysql-covid

    networks:
      - covid-network

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=covid_19

      
    volumes:
      - mysql_db:/var/lib/mysql
      
      
volumes:
  mysql_db:

networks:
  covid-network: